[project]
name = "melbourne-6"
version = "6.0.0"
description = "Scoreboard image generator"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click-loglevel>=0.6.0",
    "click>=8.1.8",
    "xlrd==1.2.0",
    "skia-python>=87.8",
    "webcolors>=24.11.1",
    "pathvalidate>=3.2.3",
    "cachetools>=5.5.2",
    "fastapi>=0.115.12",
    "pydantic-settings>=2.9.1",
    "uvicorn>=0.34.2",
    "python-multipart>=0.0.20",
    "humanfriendly>=10.0",
    "colorlog>=6.9.0",
]

[dependency-groups]
dev = [
    "mypy>=1.15.0",
    "ruff>=0.11.8",
]
