/* eslint-disable sort-keys */

/**
 * Represents one manually maintained bundled flag metadata entry.
 */
export interface BundledFlagMetadataEntry {
  details: string;
  fileName: string;
}

/**
 * Stores bundled flag metadata grouped by flag pack.
 */
export const BUNDLED_FLAG_METADATA: Record<string, BundledFlagMetadataEntry[]> =
  {
    ISC: [
      { fileName: 'Aevis.png', details: 'Aevis' },
      { fileName: 'Alardon.png', details: 'Alardon' },
      { fileName: 'Alma Livre.png', details: 'Alma Livre' },
      { fileName: 'Amsteris.png', details: 'Amsteris' },
      { fileName: 'Asankon.png', details: 'Asankon' },
      { fileName: 'Auravaan.png', details: 'Aurävaan' },
      { fileName: 'Bartlett.png', details: 'Bartlett' },
      { fileName: 'Bitland.png', details: 'Bitland' },
      { fileName: 'Blomsterhaven.png', details: 'Blomsterhaven' },
      { fileName: 'Bubblique.png', details: 'Bubblique' },
      { fileName: 'Chruno.png', details: 'Chruno' },
      { fileName: 'Crimeland-Palpatinate.png', details: 'Crimeland-Palpatinate' },
      { fileName: 'Darkria.png', details: 'Darkria' },
      { fileName: 'Daulska.png', details: 'Daǔlska' },
      { fileName: 'Deirdre and Beaubeirdre.png', details: 'Deirdre and Beaubeirdre' },
      { fileName: 'DeLuLuLand.png', details: 'DeLuLuLand' },
      { fileName: 'DimkaRUS.png', details: 'DimkaRUS' },
      { fileName: 'Dulcet Ebullience.png', details: 'Dulcet Ebullience' },
      { fileName: 'Eden Heights.png', details: 'Eden Heights' },
      { fileName: "Enot'ebia.png", details: 'Enot\'ebia' },
      { fileName: 'Eriod.png', details: 'Eriod' },
      { fileName: 'Etorkia.png', details: 'Etorkia' },
      { fileName: 'Evergreen Lands.png', details: 'Evergreen Lands' },
      { fileName: 'Falvarak.png', details: 'Faĺvarak' },
      { fileName: 'Fervorosia.jpg', details: 'Fervorosia' },
      { fileName: 'Folkloria.png', details: 'Folkloria' },
      { fileName: 'Gandhara.png', details: 'Gandhara' },
      { fileName: 'Gredst.png', details: 'Gredst' },
      { fileName: 'Grolskira.png', details: 'Grolskira' },
      { fileName: 'Hanei Caravaz.png', details: 'Ħanei Čaravāz' },
      { fileName: 'Hanzyuki.png', details: 'Hanzyuki' },
      { fileName: 'Haven.png', details: 'Haven' },
      { fileName: 'HKJIADH.png', details: 'HKJIADH' },
      { fileName: 'Irdminia.png', details: 'Irdminia' },
      { fileName: 'Isbseiro.png', details: 'Isbseiro' },
      { fileName: 'Kaledonii.png', details: 'Kaledonii' },
      { fileName: 'Kaministiquia.png', details: 'Kaministiquia' },
      { fileName: 'Kharo.jpg', details: 'Kharó' },
      { fileName: 'Kimmystan.png', details: 'Kimmystan' },
      { fileName: 'Koalatopolous.png', details: 'Koalatopolous' },
      { fileName: 'Kosma.png', details: 'Kosma' },
      { fileName: 'Kox-Zoeteweij.png', details: 'Kox-Zoeteweij' },
      { fileName: 'Lacrea.png', details: 'Lacrea' },
      { fileName: 'Ladoga.png', details: 'Ladoga' },
      { fileName: 'Lahna.png', details: 'Lahna' },
      { fileName: 'Leshia.png', details: 'Leshia' },
      { fileName: 'Lettuce.png', details: 'Lettuce' },
      { fileName: 'Levie.png', details: 'Levië' },
      { fileName: 'Luzze.png', details: 'Luzze' },
      { fileName: 'Macroland.png', details: 'Macroland' },
      { fileName: 'Marium.png', details: 'Mărium' },
      { fileName: 'Mensa.png', details: 'Mensa' },
      { fileName: 'Nickymania.png', details: 'Nickymania' },
      { fileName: "Nicolas' Neighbour.png", details: 'Nicolas\' Neighbour' },
      { fileName: 'Noxus.png', details: 'Noxus' },
      { fileName: 'Oravania.jpg', details: 'Oravania' },
      { fileName: 'Pen Island.png', details: 'Pen Island' },
      { fileName: 'Percheron.png', details: 'Percheron' },
      { fileName: 'Pinnipedia.png', details: 'Pinnipedia' },
      { fileName: 'Polland.png', details: 'Polland' },
      { fileName: 'Pono.png', details: 'Pönö' },
      { fileName: 'Radamede.png', details: 'Radamede' },
      { fileName: 'Raingate.png', details: 'Raingate' },
      { fileName: 'Rata Sum.png', details: 'Rata Sum' },
      { fileName: 'Refrainia.png', details: 'Refrainia' },
      { fileName: 'Riya-Sampetrina.png', details: 'Riya-Sampetrina' },
      { fileName: 'SEAL.png', details: 'SEAL' },
      { fileName: 'Solais X.png', details: 'Solais X' },
      { fileName: 'Spitzenbergen.png', details: 'Spitzenbergen' },
      { fileName: 'St. Eva & Lepland.png', details: 'St. Eva & Lepland' },
      { fileName: 'Stelle.png', details: 'Stelle' },
      { fileName: 'Sunetti.png', details: 'Sunetti' },
      { fileName: 'Tashkveny.png', details: 'Tashkveny' },
      { fileName: 'Territrius.png', details: 'Territrius' },
      { fileName: 'Thorway.png', details: 'Thorway' },
      { fileName: 'Tikata.png', details: 'Tikata' },
      { fileName: 'Tonallan.png', details: 'Tonallán' },
      { fileName: 'Treslend.png', details: 'Trešlend' },
      { fileName: 'Unovah.png', details: 'Unovah' },
      { fileName: 'Uubell.png', details: 'Uubell' },
      { fileName: 'Valdron.png', details: 'Valdron' },
      { fileName: 'Zephyrus.png', details: 'Zephyrus' },
    ],
    Rect: [
      { fileName: 'ad.png', details: 'Andorra' },
      { fileName: 'ae.png', details: 'United Arab Emirates' },
      { fileName: 'af.png', details: 'Afghanistan' },
      { fileName: 'ag.png', details: 'Antigua & Barbuda' },
      { fileName: 'al.png', details: 'Albania' },
      { fileName: 'am.png', details: 'Armenia' },
      { fileName: 'ao.png', details: 'Angola' },
      { fileName: 'ar.png', details: 'Argentina' },
      { fileName: 'at.png', details: 'Austria' },
      { fileName: 'au.png', details: 'Australia' },
      { fileName: 'az.png', details: 'Azerbaijan' },
      { fileName: 'ba.png', details: 'Bosnia & Herzegovina' },
      { fileName: 'bb.png', details: 'Barbados' },
      { fileName: 'bd.png', details: 'Bangladesh' },
      { fileName: 'be.png', details: 'Belgium' },
      { fileName: 'bf.png', details: 'Burkina Faso' },
      { fileName: 'bg.png', details: 'Bulgaria' },
      { fileName: 'bh.png', details: 'Bahrain' },
      { fileName: 'bi.png', details: 'Burundi' },
      { fileName: 'bj.png', details: 'Benin' },
      { fileName: 'bn.png', details: 'Brunei' },
      { fileName: 'bo.png', details: 'Bolivia' },
      { fileName: 'br.png', details: 'Brazil' },
      { fileName: 'bs.png', details: 'The Bahamas' },
      { fileName: 'bt.png', details: 'Bhutan' },
      { fileName: 'bw.png', details: 'Botswana' },
      { fileName: 'by.png', details: 'Belarus' },
      { fileName: 'bz.png', details: 'Belize' },
      { fileName: 'ca.png', details: 'Canada' },
      { fileName: 'cd.png', details: 'Democratic Republic of the Congo' },
      { fileName: 'cf.png', details: 'Central African Republic' },
      { fileName: 'cg.png', details: 'Congo' },
      { fileName: 'ch.png', details: 'Switzerland' },
      { fileName: 'ci.png', details: 'Côte d\'Ivoire (Ivory Coast)' },
      { fileName: 'cl.png', details: 'Chile' },
      { fileName: 'cm.png', details: 'Cameroon' },
      { fileName: 'cn.png', details: 'China' },
      { fileName: 'co.png', details: 'Colombia' },
      { fileName: 'cr.png', details: 'Costa Rica' },
      { fileName: 'cu.png', details: 'Cuba' },
      { fileName: 'cv.png', details: 'Cabo Verde' },
      { fileName: 'cy.png', details: 'Cyprus' },
      { fileName: 'cz.png', details: 'Czech Republic' },
      { fileName: 'de.png', details: 'Germany' },
      { fileName: 'dj.png', details: 'Djibouti' },
      { fileName: 'dk.png', details: 'Denmark' },
      { fileName: 'dm.png', details: 'Dominica' },
      { fileName: 'do.png', details: 'Dominican Republic' },
      { fileName: 'dz.png', details: 'Algeria' },
      { fileName: 'ec.png', details: 'Ecuador' },
      { fileName: 'ee.png', details: 'Estonia' },
      { fileName: 'eg.png', details: 'Egypt' },
      { fileName: 'eh.png', details: 'Western Sahara' },
      { fileName: 'er.png', details: 'Eritrea' },
      { fileName: 'es.png', details: 'Spain' },
      { fileName: 'et.png', details: 'Ethiopia' },
      { fileName: 'fi.png', details: 'Finland' },
      { fileName: 'fj.png', details: 'Fiji' },
      { fileName: 'fm.png', details: 'Micronesia' },
      { fileName: 'fr.png', details: 'France' },
      { fileName: 'ga.png', details: 'Gabon' },
      { fileName: 'gb.png', details: 'United Kingdom' },
      { fileName: 'gd.png', details: 'Grenada' },
      { fileName: 'ge.png', details: 'Georgia' },
      { fileName: 'gh.png', details: 'Ghana' },
      { fileName: 'gm.png', details: 'The Gambia' },
      { fileName: 'gn.png', details: 'Guinea' },
      { fileName: 'gq.png', details: 'Equatorial Guinea' },
      { fileName: 'gr.png', details: 'Greece' },
      { fileName: 'gt.png', details: 'Guatemala' },
      { fileName: 'gw.png', details: 'Guinea-Bissau' },
      { fileName: 'gy.png', details: 'Guyana' },
      { fileName: 'hn.png', details: 'Honduras' },
      { fileName: 'hr.png', details: 'Croatia' },
      { fileName: 'ht.png', details: 'Haiti' },
      { fileName: 'hu.png', details: 'Hungary' },
      { fileName: 'id.png', details: 'Indonesia' },
      { fileName: 'ie.png', details: 'Ireland' },
      { fileName: 'il.png', details: 'Israel' },
      { fileName: 'in.png', details: 'India' },
      { fileName: 'iq.png', details: 'Iraq' },
      { fileName: 'ir.png', details: 'Iran' },
      { fileName: 'is.png', details: 'Iceland' },
      { fileName: 'it.png', details: 'Italy' },
      { fileName: 'jm.png', details: 'Jamaica' },
      { fileName: 'jo.png', details: 'Jordan' },
      { fileName: 'jp.png', details: 'Japan' },
      { fileName: 'ke.png', details: 'Kenya' },
      { fileName: 'kg.png', details: 'Kyrgyzstan' },
      { fileName: 'kh.png', details: 'Cambodia' },
      { fileName: 'ki.png', details: 'Kiribati' },
      { fileName: 'km.png', details: 'Comoros' },
      { fileName: 'kn.png', details: 'St. Kitts & Nevis' },
      { fileName: 'kp.png', details: 'North Korea' },
      { fileName: 'kr.png', details: 'South Korea' },
      { fileName: 'ks.png', details: 'Kosovo' },
      { fileName: 'kw.png', details: 'Kuwait' },
      { fileName: 'kz.png', details: 'Kazakhstan' },
      { fileName: 'la.png', details: 'Laos' },
      { fileName: 'lb.png', details: 'Lebanon' },
      { fileName: 'lc.png', details: 'St. Lucia' },
      { fileName: 'li.png', details: 'Liechtenstein' },
      { fileName: 'lk.png', details: 'Sri Lanka' },
      { fileName: 'lr.png', details: 'Liberia' },
      { fileName: 'ls.png', details: 'Lesotho' },
      { fileName: 'lt.png', details: 'Lithuania' },
      { fileName: 'lu.png', details: 'Luxembourg' },
      { fileName: 'lv.png', details: 'Latvia' },
      { fileName: 'ly.png', details: 'Libya' },
      { fileName: 'ma.png', details: 'Morocco' },
      { fileName: 'mc.png', details: 'Monaco' },
      { fileName: 'md.png', details: 'Moldova' },
      { fileName: 'me.png', details: 'Montenegro' },
      { fileName: 'mg.png', details: 'Madagascar' },
      { fileName: 'mh.png', details: 'Marshall Islands' },
      { fileName: 'mk.png', details: 'North Macedonia' },
      { fileName: 'ml.png', details: 'Mali' },
      { fileName: 'mm.png', details: 'Myanmar' },
      { fileName: 'mn.png', details: 'Mongolia' },
      { fileName: 'mr.png', details: 'Mauritania' },
      { fileName: 'mt.png', details: 'Malta' },
      { fileName: 'mu.png', details: 'Mauritius' },
      { fileName: 'mv.png', details: 'Maldives' },
      { fileName: 'mw.png', details: 'Malawi' },
      { fileName: 'mx.png', details: 'Mexico' },
      { fileName: 'my.png', details: 'Malaysia' },
      { fileName: 'mz.png', details: 'Mozambique' },
      { fileName: 'na.png', details: 'Namibia' },
      { fileName: 'ne.png', details: 'Niger' },
      { fileName: 'ng.png', details: 'Nigeria' },
      { fileName: 'ni.png', details: 'Nicaragua' },
      { fileName: 'nl.png', details: 'Netherlands' },
      { fileName: 'no.png', details: 'Norway' },
      { fileName: 'np.png', details: 'Nepal' },
      { fileName: 'nr.png', details: 'Nauru' },
      { fileName: 'nz.png', details: 'New Zealand' },
      { fileName: 'om.png', details: 'Oman' },
      { fileName: 'pa.png', details: 'Panama' },
      { fileName: 'pe.png', details: 'Peru' },
      { fileName: 'pg.png', details: 'Papua New Guinea' },
      { fileName: 'ph.png', details: 'The Philippines' },
      { fileName: 'pk.png', details: 'Pakistan' },
      { fileName: 'pl.png', details: 'Poland' },
      { fileName: 'pt.png', details: 'Portugal' },
      { fileName: 'pw.png', details: 'Palau' },
      { fileName: 'py.png', details: 'Paraguay' },
      { fileName: 'qa.png', details: 'Qatar' },
      { fileName: 'ro.png', details: 'Romania' },
      { fileName: 'rs.png', details: 'Serbia' },
      { fileName: 'ru.png', details: 'Russia' },
      { fileName: 'rw.png', details: 'Rwanda' },
      { fileName: 'sa.png', details: 'Saudi Arabia' },
      { fileName: 'sb.png', details: 'Solomon Islands' },
      { fileName: 'sc.png', details: 'Seychelles' },
      { fileName: 'sd.png', details: 'Sudan' },
      { fileName: 'se.png', details: 'Sweden' },
      { fileName: 'serbiamontenegro.png', details: 'Serbia & Montenegro' },
      { fileName: 'sg.png', details: 'Singapore' },
      { fileName: 'si.png', details: 'Slovenia' },
      { fileName: 'sk.png', details: 'Slovakia' },
      { fileName: 'sl.png', details: 'Sierra Leone' },
      { fileName: 'sm.png', details: 'San Marino' },
      { fileName: 'sn.png', details: 'Senegal' },
      { fileName: 'so.png', details: 'Somalia' },
      { fileName: 'sr.png', details: 'Suriname' },
      { fileName: 'st.png', details: 'São Tomé and Príncipe' },
      { fileName: 'sv.png', details: 'El Salvador' },
      { fileName: 'sy.png', details: 'Syria' },
      { fileName: 'sz.png', details: 'eSwatini' },
      { fileName: 'td.png', details: 'Chad' },
      { fileName: 'tg.png', details: 'Togo' },
      { fileName: 'th.png', details: 'Thailand' },
      { fileName: 'tj.png', details: 'Tajikistan' },
      { fileName: 'tl.png', details: 'Timor Leste' },
      { fileName: 'tm.png', details: 'Turkmenistan' },
      { fileName: 'tn.png', details: 'Tunisia' },
      { fileName: 'to.png', details: 'Tonga' },
      { fileName: 'tr.png', details: 'Turkey' },
      { fileName: 'tt.png', details: 'Trinidad & Tobago' },
      { fileName: 'tv.png', details: 'Tuvalu' },
      { fileName: 'tw.png', details: 'Taiwan' },
      { fileName: 'tz.png', details: 'Tanzania' },
      { fileName: 'ua.png', details: 'Ukraine' },
      { fileName: 'ug.png', details: 'Uganda' },
      { fileName: 'us.png', details: 'United States' },
      { fileName: 'uy.png', details: 'Uruguay' },
      { fileName: 'uz.png', details: 'Uzbekistan' },
      { fileName: 'va.png', details: 'Vatican City' },
      { fileName: 'vc.png', details: 'Saint Vincent and the Grenadines' },
      { fileName: 've.png', details: 'Venezuela' },
      { fileName: 'vn.png', details: 'Vietnam' },
      { fileName: 'vu.png', details: 'Vanuatu' },
      { fileName: 'ws.png', details: 'Samoa' },
      { fileName: 'xk.png', details: 'Kosovo' },
      { fileName: 'ye.png', details: 'Yemen' },
      { fileName: 'yu.png', details: 'Yugoslavia' },
      { fileName: 'za.png', details: 'South Africa' },
      { fileName: 'zm.png', details: 'Zambia' },
      { fileName: 'zw.png', details: 'Zimbabwe' },
    ],
    World: [
      { fileName: 'ad.png', details: 'Andorra' },
      { fileName: 'ae.png', details: 'United Arab Emirates' },
      { fileName: 'af.png', details: 'Afghanistan' },
      { fileName: 'ag.png', details: 'Antigua & Barbuda' },
      { fileName: 'ai.png', details: 'Anguilla' },
      { fileName: 'al.png', details: 'Albania' },
      { fileName: 'am.png', details: 'Armenia' },
      { fileName: 'ao.png', details: 'Angola' },
      { fileName: 'aq.png', details: 'Antarctica' },
      { fileName: 'ar.png', details: 'Argentina' },
      { fileName: 'as.png', details: 'American Samoa' },
      { fileName: 'at.png', details: 'Austria' },
      { fileName: 'au.png', details: 'Australia' },
      { fileName: 'aw.png', details: 'Aruba' },
      { fileName: 'ax.png', details: 'Åland Islands' },
      { fileName: 'az.png', details: 'Azerbaijan' },
      { fileName: 'ba.png', details: 'Bosnia & Herzegovina' },
      { fileName: 'bb.png', details: 'Barbados' },
      { fileName: 'bd.png', details: 'Bangladesh' },
      { fileName: 'be.png', details: 'Belgium' },
      { fileName: 'bf.png', details: 'Burkina Faso' },
      { fileName: 'bg.png', details: 'Bulgaria' },
      { fileName: 'bh.png', details: 'Bahrain' },
      { fileName: 'bi.png', details: 'Burundi' },
      { fileName: 'bj.png', details: 'Benin' },
      { fileName: 'bl.png', details: 'Saint Barthélemy' },
      { fileName: 'bm.png', details: 'Bermuda' },
      { fileName: 'bn.png', details: 'Brunei' },
      { fileName: 'bo.png', details: 'Bolivia' },
      { fileName: 'bq.png', details: 'Netherlands Antilles' },
      { fileName: 'br.png', details: 'Brazil' },
      { fileName: 'bs.png', details: 'The Bahamas' },
      { fileName: 'bt.png', details: 'Bhutan' },
      { fileName: 'bv.png', details: 'Bouvet Island' },
      { fileName: 'bw.png', details: 'Botswana' },
      { fileName: 'by.png', details: 'Belarus' },
      { fileName: 'by-alt.png', details: 'Belarus (1918)' },
      { fileName: 'bz.png', details: 'Belize' },
      { fileName: 'ca.png', details: 'Canada' },
      { fileName: 'cc.png', details: 'Cocos Islands' },
      { fileName: 'cd.png', details: 'Democratic Republic of the Congo' },
      { fileName: 'cf.png', details: 'Central African Republic' },
      { fileName: 'cg.png', details: 'Congo' },
      { fileName: 'ch.png', details: 'Switzerland' },
      { fileName: 'ci.png', details: 'Côte d\'Ivoire (Ivory Coast)' },
      { fileName: 'ck.png', details: 'Cook Islands (New Zealand)' },
      { fileName: 'cl.png', details: 'Chile' },
      { fileName: 'cm.png', details: 'Cameroon' },
      { fileName: 'cn.png', details: 'China' },
      { fileName: 'co.png', details: 'Colombia' },
      { fileName: 'cr.png', details: 'Costa Rica' },
      { fileName: 'cu.png', details: 'Cuba' },
      { fileName: 'cv.png', details: 'Cabo Verde' },
      { fileName: 'cw.png', details: 'Curaçao (Netherlands)' },
      { fileName: 'cx.png', details: 'Christmas Island (Australia)' },
      { fileName: 'cy.png', details: 'Cyprus' },
      { fileName: 'cz.png', details: 'Czech Republic' },
      { fileName: 'de.png', details: 'Germany' },
      { fileName: 'dj.png', details: 'Djibouti' },
      { fileName: 'dk.png', details: 'Denmark' },
      { fileName: 'dm.png', details: 'Dominica' },
      { fileName: 'do.png', details: 'Dominican Republic' },
      { fileName: 'dz.png', details: 'Algeria' },
      { fileName: 'ec.png', details: 'Ecuador' },
      { fileName: 'ee.png', details: 'Estonia' },
      { fileName: 'eg.png', details: 'Egypt' },
      { fileName: 'eh.png', details: 'Western Sahara' },
      { fileName: 'er.png', details: 'Eritrea' },
      { fileName: 'es.png', details: 'Spain' },
      { fileName: 'et.png', details: 'Ethiopia' },
      { fileName: 'fi.png', details: 'Finland' },
      { fileName: 'fj.png', details: 'Fiji' },
      { fileName: 'fk.png', details: 'Falkland Islands' },
      { fileName: 'fm.png', details: 'Micronesia' },
      { fileName: 'fo.png', details: 'Faroe Islands' },
      { fileName: 'fr.png', details: 'France' },
      { fileName: 'ga.png', details: 'Gabon' },
      { fileName: 'gb.png', details: 'United Kingdom' },
      { fileName: 'gd.png', details: 'Grenada' },
      { fileName: 'ge.png', details: 'Georgia' },
      { fileName: 'gf.png', details: 'French Guiana' },
      { fileName: 'gg.png', details: 'Guernsey' },
      { fileName: 'gh.png', details: 'Ghana' },
      { fileName: 'gi.png', details: 'Gibraltar' },
      { fileName: 'gl.png', details: 'Greenland' },
      { fileName: 'gm.png', details: 'The Gambia' },
      { fileName: 'gn.png', details: 'Guinea' },
      { fileName: 'gp.png', details: 'Guadeloupe' },
      { fileName: 'gq.png', details: 'Equatorial Guinea' },
      { fileName: 'gr.png', details: 'Greece' },
      { fileName: 'gs.png', details: 'South Georgia and the South Sandwch Islands' },
      { fileName: 'gt.png', details: 'Guatemala' },
      { fileName: 'gu.png', details: 'Guam' },
      { fileName: 'gw.png', details: 'Guinea-Bissau' },
      { fileName: 'gy.png', details: 'Guyana' },
      { fileName: 'hk.png', details: 'Hong Kong' },
      { fileName: 'hm.png', details: 'Heard Island and McDonald Islands' },
      { fileName: 'hn.png', details: 'Honduras' },
      { fileName: 'hr.png', details: 'Croatia' },
      { fileName: 'ht.png', details: 'Haiti' },
      { fileName: 'hu.png', details: 'Hungary' },
      { fileName: 'id.png', details: 'Indonesia' },
      { fileName: 'ie.png', details: 'Ireland' },
      { fileName: 'il.png', details: 'Israel' },
      { fileName: 'im.png', details: 'Isle of Man' },
      { fileName: 'in.png', details: 'India' },
      { fileName: 'io.png', details: 'British Indian Ocean Territory' },
      { fileName: 'iq.png', details: 'Iraq' },
      { fileName: 'ir.png', details: 'Iran' },
      { fileName: 'is.png', details: 'Iceland' },
      { fileName: 'it.png', details: 'Italy' },
      { fileName: 'je.png', details: 'Jersey (UK)' },
      { fileName: 'jm.png', details: 'Jamaica' },
      { fileName: 'jo.png', details: 'Jordan' },
      { fileName: 'jp.png', details: 'Japan' },
      { fileName: 'ke.png', details: 'Kenya' },
      { fileName: 'kg.png', details: 'Kyrgyzstan' },
      { fileName: 'kh.png', details: 'Cambodia' },
      { fileName: 'ki.png', details: 'Kiribati' },
      { fileName: 'km.png', details: 'Comoros' },
      { fileName: 'kn.png', details: 'St. Kitts & Nevis' },
      { fileName: 'kp.png', details: 'North Korea' },
      { fileName: 'kr.png', details: 'South Korea' },
      { fileName: 'kw.png', details: 'Kuwait' },
      { fileName: 'ky.png', details: 'Cayman Islands' },
      { fileName: 'kz.png', details: 'Kazakhstan' },
      { fileName: 'la.png', details: 'Laos' },
      { fileName: 'lb.png', details: 'Lebanon' },
      { fileName: 'lc.png', details: 'St. Lucia' },
      { fileName: 'li.png', details: 'Liechtenstein' },
      { fileName: 'lk.png', details: 'Sri Lanka' },
      { fileName: 'lr.png', details: 'Liberia' },
      { fileName: 'ls.png', details: 'Lesotho' },
      { fileName: 'lt.png', details: 'Lithuania' },
      { fileName: 'lu.png', details: 'Luxembourg' },
      { fileName: 'lv.png', details: 'Latvia' },
      { fileName: 'ly.png', details: 'Libya' },
      { fileName: 'ma.png', details: 'Morocco' },
      { fileName: 'mc.png', details: 'Monaco' },
      { fileName: 'md.png', details: 'Moldova' },
      { fileName: 'me.png', details: 'Montenegro' },
      { fileName: 'mf.png', details: 'Saint Martin' },
      { fileName: 'mg.png', details: 'Madagascar' },
      { fileName: 'mh.png', details: 'Marshall Islands' },
      { fileName: 'mk.png', details: 'North Macedonia' },
      { fileName: 'ml.png', details: 'Mali' },
      { fileName: 'mm.png', details: 'Myanmar' },
      { fileName: 'mn.png', details: 'Mongolia' },
      { fileName: 'mo.png', details: 'Macau' },
      { fileName: 'mp.png', details: 'Northern Mariana Islands' },
      { fileName: 'mq.png', details: 'Martinique' },
      { fileName: 'mr.png', details: 'Mauritania' },
      { fileName: 'ms.png', details: 'Montserrat' },
      { fileName: 'mt.png', details: 'Malta' },
      { fileName: 'mu.png', details: 'Mauritius' },
      { fileName: 'mv.png', details: 'Maldives' },
      { fileName: 'mw.png', details: 'Malawi' },
      { fileName: 'mx.png', details: 'Mexico' },
      { fileName: 'my.png', details: 'Malaysia' },
      { fileName: 'mz.png', details: 'Mozambique' },
      { fileName: 'na.png', details: 'Namibia' },
      { fileName: 'nc.png', details: 'New Caledonia' },
      { fileName: 'ne.png', details: 'Niger' },
      { fileName: 'nf.png', details: 'Norfolk Island' },
      { fileName: 'ng.png', details: 'Nigeria' },
      { fileName: 'ni.png', details: 'Nicaragua' },
      { fileName: 'nl.png', details: 'Netherlands' },
      { fileName: 'no.png', details: 'Norway' },
      { fileName: 'np.png', details: 'Nepal' },
      { fileName: 'nr.png', details: 'Nauru' },
      { fileName: 'nu.png', details: 'Niue' },
      { fileName: 'nz.png', details: 'New Zealand' },
      { fileName: 'om.png', details: 'Oman' },
      { fileName: 'pa.png', details: 'Panama' },
      { fileName: 'pe.png', details: 'Peru' },
      { fileName: 'pf.png', details: 'French Polynesia' },
      { fileName: 'pg.png', details: 'Papua New Guinea' },
      { fileName: 'ph.png', details: 'The Philippines' },
      { fileName: 'pk.png', details: 'Pakistan' },
      { fileName: 'pl.png', details: 'Poland' },
      { fileName: 'pm.png', details: 'Saint Pierre and Miquelon' },
      { fileName: 'pn.png', details: 'Pitcairn' },
      { fileName: 'pr.png', details: 'Puerto Rico' },
      { fileName: 'ps.png', details: 'Palestine' },
      { fileName: 'pt.png', details: 'Portugal' },
      { fileName: 'pw.png', details: 'Palau' },
      { fileName: 'py.png', details: 'Paraguay' },
      { fileName: 'qa.png', details: 'Qatar' },
      { fileName: 're.png', details: 'Réunion' },
      { fileName: 'ro.png', details: 'Romania' },
      { fileName: 'rs.png', details: 'Serbia' },
      { fileName: 'ru.png', details: 'Russia' },
      { fileName: 'rw.png', details: 'Rwanda' },
      { fileName: 'sa.png', details: 'Saudi Arabia' },
      { fileName: 'sb.png', details: 'Solomon Islands' },
      { fileName: 'sc.png', details: 'Seychelles' },
      { fileName: 'sd.png', details: 'Sudan' },
      { fileName: 'se.png', details: 'Sweden' },
      { fileName: 'serbiamontenegro.png', details: 'Serbia & Montenegro' },
      { fileName: 'sg.png', details: 'Singapore' },
      { fileName: 'sh.png', details: 'St. Helena' },
      { fileName: 'si.png', details: 'Slovenia' },
      { fileName: 'sj.png', details: 'Svalbard and Jan Mayen' },
      { fileName: 'sk.png', details: 'Slovakia' },
      { fileName: 'sl.png', details: 'Sierra Leone' },
      { fileName: 'sm.png', details: 'San Marino' },
      { fileName: 'sn.png', details: 'Senegal' },
      { fileName: 'so.png', details: 'Somalia' },
      { fileName: 'sr.png', details: 'Suriname' },
      { fileName: 'ss.png', details: 'South Sudan' },
      { fileName: 'st.png', details: 'São Tomé and Príncipe' },
      { fileName: 'sv.png', details: 'El Salvador' },
      { fileName: 'sx.png', details: 'Sint Maarten' },
      { fileName: 'sy.png', details: 'Syria' },
      { fileName: 'sz.png', details: 'eSwatini' },
      { fileName: 'tc.png', details: 'Turks and Caicos' },
      { fileName: 'td.png', details: 'Chad' },
      { fileName: 'tf.png', details: 'French Southern Territories' },
      { fileName: 'tg.png', details: 'Togo' },
      { fileName: 'th.png', details: 'Thailand' },
      { fileName: 'tj.png', details: 'Tajikistan' },
      { fileName: 'tk.png', details: 'Tokelau' },
      { fileName: 'tl.png', details: 'Timor Leste' },
      { fileName: 'tm.png', details: 'Turkmenistan' },
      { fileName: 'tn.png', details: 'Tunisia' },
      { fileName: 'to.png', details: 'Tonga' },
      { fileName: 'tr.png', details: 'Turkey' },
      { fileName: 'tt.png', details: 'Trinidad & Tobago' },
      { fileName: 'tv.png', details: 'Tuvalu' },
      { fileName: 'tw.png', details: 'Taiwan' },
      { fileName: 'tz.png', details: 'Tanzania' },
      { fileName: 'ua.png', details: 'Ukraine' },
      { fileName: 'ug.png', details: 'Uganda' },
      { fileName: 'uk.png', details: 'United Kingdom' },
      { fileName: 'um.png', details: 'Northern Mariana Islands' },
      { fileName: 'us.png', details: 'United States' },
      { fileName: 'uy.png', details: 'Uruguay' },
      { fileName: 'uz.png', details: 'Uzbekistan' },
      { fileName: 'va.png', details: 'Vatican City' },
      { fileName: 'vc.png', details: 'Saint Vincent and the Grenadines' },
      { fileName: 've.png', details: 'Venezuela' },
      { fileName: 'vg.png', details: 'British Virgin Islands' },
      { fileName: 'vi.png', details: 'US Virgin Islands' },
      { fileName: 'vn.png', details: 'Vietnam' },
      { fileName: 'vu.png', details: 'Vanuatu' },
      { fileName: 'wf.png', details: 'Wallis and Futuna' },
      { fileName: 'ws.png', details: 'Samoa' },
      { fileName: 'xk.png', details: 'Kosovo' },
      { fileName: 'ye.png', details: 'Yemen' },
      { fileName: 'yt.png', details: 'Mayotte' },
      { fileName: 'yu.png', details: 'Yugoslavia' },
      { fileName: 'za.png', details: 'South Africa' },
      { fileName: 'zm.png', details: 'Zambia' },
      { fileName: 'zw.png', details: 'Zimbabwe' },
    ],
  };
